"""Command-line arguments."""

from __future__ import annotations

import argparse


def parse_args():
    p = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    p.add_argument("--mode", choices=("train", "predict"), default="train")
    p.add_argument("--dataset_root", default="")
    p.add_argument("--work_dir", default="/data/runs/chair_dinov2_lrm_render")
    p.add_argument("--exclude_uids", default="")
    p.add_argument("--max_objects", type=int, default=0)
    p.add_argument("--dinov2_model", default="dinov2_vitl14_reg")
    p.add_argument("--image_size", type=int, default=518)
    p.add_argument("--batch_size", type=int, default=1)
    p.add_argument("--grad_accum", type=int, default=8)
    p.add_argument("--patch_size", type=int, default=32)
    p.add_argument("--samples_per_ray", type=int, default=64)
    p.add_argument("--geometry_queries", type=int, default=4096)
    p.add_argument("--near", type=float, default=2.0)
    p.add_argument("--far", type=float, default=7.0)
    p.add_argument("--ray_jitter", action="store_true", default=True)
    p.add_argument("--no_ray_jitter", action="store_false", dest="ray_jitter")
    p.add_argument("--foreground_patch_prob", type=float, default=0.75)
    p.add_argument("--same_view_prob", type=float, default=0.0)
    p.add_argument("--plane_size", type=int, default=128)
    p.add_argument("--plane_channels", type=int, default=48)
    p.add_argument("--decoder_hidden", type=int, default=384)
    p.add_argument("--decoder_layers", type=int, default=5)
    p.add_argument("--latent_dim", type=int, default=1024)
    p.add_argument("--epochs", type=int, default=60)
    p.add_argument("--lr", type=float, default=8e-5)
    p.add_argument("--encoder_lr", type=float, default=2e-6)
    p.add_argument("--weight_decay", type=float, default=0.03)
    p.add_argument("--unfreeze_encoder_epoch", type=int, default=20)
    p.add_argument("--foreground_rgb_weight", type=float, default=4.0)
    p.add_argument("--background_rgb_weight", type=float, default=0.05)
    p.add_argument("--mask_weight", type=float, default=0.35)
    p.add_argument("--foreground_mask_weight", type=float, default=1.0)
    p.add_argument("--background_mask_weight", type=float, default=0.05)
    p.add_argument("--mask_recall_weight", type=float, default=0.0)
    p.add_argument("--opacity_weight", type=float, default=0.04)
    p.add_argument("--distortion_weight", type=float, default=0.002)
    p.add_argument("--geometry_weight", type=float, default=0.08)
    p.add_argument("--perceptual_weight", type=float, default=0.04)
    p.add_argument("--geometry_warmup_epochs", type=int, default=3)
    p.add_argument("--warmup_mask_mult", type=float, default=1.6)
    p.add_argument("--warmup_opacity_mult", type=float, default=1.5)
    p.add_argument("--warmup_geometry_mult", type=float, default=1.8)
    p.add_argument("--sigma_init_bias", type=float, default=0.5)
    p.add_argument("--sigma_activation_bias", type=float, default=0.0)
    p.add_argument("--charbonnier_eps", type=float, default=1e-3)
    p.add_argument("--background", type=float, nargs=3, default=(219 / 255.0, 222 / 255.0, 224 / 255.0))
    p.add_argument("--amp", choices=("none", "fp16", "bf16"), default="bf16")
    p.add_argument("--num_workers", type=int, default=12)
    p.add_argument("--crop", action="store_true", default=True)
    p.add_argument("--no_crop", action="store_false", dest="crop")
    p.add_argument("--train_ratio", type=float, default=0.8)
    p.add_argument("--val_ratio", type=float, default=0.1)
    p.add_argument("--val_batches", type=int, default=80)
    p.add_argument("--preview_every", type=int, default=1)
    p.add_argument("--preview_size", type=int, default=128)
    p.add_argument("--preview_ray_chunk", type=int, default=4096)
    p.add_argument("--preview_same_view", action="store_true")
    p.add_argument("--log_every", type=int, default=50)
    p.add_argument("--grad_clip", type=float, default=1.0)
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--skip_install", action="store_true")
    p.add_argument("--require_cuda", action="store_true")
    p.add_argument("--resume_checkpoint", default="")
    p.add_argument("--checkpoint", default="")
    p.add_argument("--image", default="")
    p.add_argument("--mask", default="")
    p.add_argument("--output_dir", default="/data/runs/chair_lrm_predict")
    p.add_argument("--grid_resolution", type=int, default=160)
    p.add_argument("--sigma_level", type=float, default=8.0)
    p.add_argument("--predict_chunk", type=int, default=262144)
    return p.parse_args()

